social/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [
                  path('login_costom/', views.login_costom, name='login_costom'),
                  path('logout_/', views.logout_, name='logout_'),
                  path('register/', views.register, name='register'),
                  path('profile/', views.profile, name='profile'),
                  path('rules/', views.Rules.as_view(), name='rules'),
                  path('ends/', views.Ends.as_view(), name='ends'),
                  path('password_check/', views.password_check, name='password_check'),
                  # path('phone_check/', views.phone_check, name='phone_check'),
                  path('forget_password/', views.ForgetPassword.as_view(), name='forget_password'),
                  path('password_reset_done/', views.ResetDone.as_view(), name='password_reset_done'),
                  path('confirm_password/<uidb64>/<token>/', views.ConfirmPassword.as_view(), name='confirm_password'),
                  path('confirm_done/', views.ConfirmDone.as_view(), name='confirm_done'),

              ]

social/direct/urls.py
from django.urls import path
from . import views

app_name = 'direct'
urlpatterns = [
    path('<int:idu>/<int:id_>/', views.direct, name='direct'),
    path('search/', views.search, name='search'),
    path('direct_list/', views.direct_list, name='direct_list'),
    path('new_notif/', views.new_notif, name='new_notif'),
    path('block/<int:id>/', views.block, name='block'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('advertise/', views.advertise, name='advertise'),
    path('create_advertise/', views.create_advertise, name='create_advertise'),
    # path('modify_advertise/<int:id>/', views.modify_advertise, name='modify_advertise'),
    path('alaki/',views.alaki,name='alaki'),
]

social/social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('topic/', include('topic.urls', namespace='topic')),
                  path('direct/', include('direct.urls', namespace='direct')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

social/topic/urls.py
from django.urls import path, re_path
from . import views

app_name = 'topic'
urlpatterns = [
    path('creat_topic/', views.creat_topic, name='creat_topic'),
    path('most_reacts/', views.MostReacts.as_view(), name='most_reacts'),
    re_path(r'public_topic/(?P<id>\d+)/(?P<slug_topic>[-\w]+)/$', views.public_topic, name='public_topic'),
    path('main/', views.main, name='main'),
    path('like/<int:id>/<str:like_>/<int:id_res>/', views.like, name='like'),
    path('like/<int:id>/<str:like_>/', views.like, name='like_topic'),
    # path('dislike/<int:id>/<str:like_>/<int:id_res>/', views.dislike, name='dislike'),
    path('user_topics/<int:id>/', views.user_topics, name='user_topics'),
    path('report/<int:id>/', views.report, name='report_top'),
    path('report/<int:id>/<int:id_res>/', views.report, name='report_rec'),

]

social/direct/models.py
from django.db import models
from accounts.models import *
from django.db.models.signals import post_save
from django_jalali.db import models as jmodels
from jdatetime import datetime
from datetime import timedelta


class Advertise(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    allowed = models.BooleanField(default=False)
    subject = models.CharField(max_length=40)
    image = models.ImageField(upload_to='advertise', blank=True, null=True)
    text = models.TextField(max_length=500)
    create = jmodels.jDateTimeField(auto_now_add=True)
    exp_date = jmodels.jDateTimeField(default=datetime.now() + timedelta(days=30))


# Create your models here.
class RoomateU(models.Model):
    block = models.BooleanField(default=False)
    on = models.IntegerField()
    man = models.IntegerField()

    def __str__(self):
        return str(self.id)


class DirectionU(models.Model):
    message = models.TextField(max_length=400)
    date = jmodels.jDateTimeField(auto_now_add=True)
    roomate = models.ForeignKey(RoomateU, on_delete=models.CASCADE,related_name='direction')
    he_she = models.ForeignKey(User, on_delete=models.CASCADE)


class Seen(models.Model):
    person = models.ForeignKey(User, on_delete=models.CASCADE)
    roome = models.OneToOneField(RoomateU, on_delete=models.CASCADE)
    visit = jmodels.jDateTimeField(auto_now=True)


def save_seen(sender, **kwargs):
    if kwargs['created']:
        los = Seen(roome=kwargs['instance'], person_id=kwargs['instance'].man, visit=datetime.now())
        los.save()


post_save.connect(save_seen, sender=RoomateU)

social/direct/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from .models import *
from accounts.models import *
from django.contrib import messages
from .form import *
from django.db.models import Q
from django.core.mail import EmailMessage

room = None

def alaki(request):
    user= User.objects.get(id=2)
    return HttpResponse(user)
# Create your views here.
@login_required(login_url='accounts:login_costom')
def direct(request, idu, id_):
    get_object_or_404(User, id=id_, is_block=False)
    get_object_or_404(User, id=idu, is_block=False)
    if request.method == 'GET':
        form = DirectForm()
        if not RoomateU.objects.filter(on=idu, man=id_).values('on', 'man', ).exists() and not RoomateU.objects.filter(
                on=id_, man=idu).values('on', 'man', ).exists():
            pos = RoomateU(on=idu, man=id_)
            pos.save()
        if id_ == request.user.id or idu == request.user.id:
            global roomate
            if RoomateU.objects.filter(on=idu, man=id_).values('on', 'man', ).exists():
                roomate = RoomateU.objects.get(on=idu, man=id_)
            else:
                roomate = RoomateU.objects.get(on=id_, man=idu)
            dir = DirectionU.objects.filter(roomate_id=roomate.id).values('roomate_id', 'he_she_id', 'date').last()
            if dir:
                see = Seen.objects.get(roome_id=roomate.id)
                if dir['he_she_id'] != request.user.id and dir['date'] > see.visit:
                    see.person_id = request.user.id
                    see.save()

            directs = DirectionU.objects.filter(roomate_id=roomate.id).order_by('-date')
            return render(request, 'direct/direct.html', {'directs': directs, 'roomate': roomate, 'form': form, })
        else:
            messages.error(request, 'برای  گفتوگو وارد حساب خود شوید')
            return redirect('topic:main')

    if request.method == 'POST':
        form = DirectForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            pire = DirectionU(message=data['message'], he_she_id=request.user.id, roomate_id=roomate.id)
            pire.save()
        else:
            messages.error(request, 'لطفا فیلد مقابل را پر کنید')
        return redirect('direct:direct', idu, id_)


@login_required(login_url='accounts:login_costom')
def search(request):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'GET':
        form = SearchForm()
        users = User.objects
        if request.GET.get('search'):
            users = users.filter(username__icontains=request.GET.get('search'), is_active=True, is_block=False).values(
                'id', 'username', )
        else:
            users = users.filter(is_active=True, is_block=False).values('id', 'username', )
        return render(request, 'direct/search.html', {'form': form, 'users': users})
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            if data['search']:
                return redirect('direct:direct', data['search'], request.user.id)
        else:
            return redirect(url)


@login_required(login_url='accounts:login_costom')
def handle_notif(request):
    rooms = RoomateU.objects.filter(Q(on=request.user.id) | Q(man=request.user.id))
    persons = []
    not_seens = []
    for rooj in rooms:
        if not rooj.block:
            if not User.objects.get(id=rooj.on).is_block and not User.objects.get(id=rooj.man).is_block:
                person = User.objects.get(id=rooj.on)
                if person.id == request.user.id:
                    person = User.objects.get(id=rooj.man)
                dir = DirectionU.objects.filter(roomate_id=rooj.id).values('he_she_id', 'date', ).last()
                if dir:
                    see = Seen.objects.get(roome_id=rooj.id)
                    if dir['he_she_id'] != request.user.id and dir['date'] > see.visit:
                        not_seens.append(person)
                persons.append(person)
    return {'persons': persons, 'not_seens': not_seens}


@login_required(login_url='accounts:login_costom')
def new_notif(request):
    custom = handle_notif(request)
    return len(custom['not_seens'])


@login_required(login_url='accounts:login_costom')
def direct_list(request):
    custom = handle_notif(request)
    return render(request, 'direct/direct_list.html', custom)


def block(request, id):
    if request.method == 'POST':
        roos = get_object_or_404(RoomateU, id=id)
        directs = roos.direction.all()
        for dire in directs:
            dire.delete()
        roos.block = True
        roos.save()
        messages.warning(request, 'اتاق گفتوگو بنا به در خواست شما بلاک شد!')
    return redirect('direct:direct_list')


@login_required(login_url='accounts:login_costom')
def create_advertise(request):
    if request.method == 'GET' and request.user.action:
        form = AdvertiseForm()
        return render(request, 'direct/create_advertise.html', {'form': form, })
    if request.method == 'POST':
        form = AdvertiseForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            sus = Advertise(user_id=request.user.id, subject=data['subject'], image=data['image'], text=data['text'])
            request.user.action -= 1
            request.user.save()
            sus.save()
            messages.success(request, 'اگهی شما ایجاد شد ، پس از بررسی ادمین منتشر خواهد شد')
        else:
            messages.error(request, 'اطلاعات وارد شده صحیح نیست')
        return redirect('direct:advertise')
    else:
        return redirect('topic:main')


@login_required(login_url='accounts:login_costom')
# def modify_advertise(request, id):
#     adver = get_object_or_404(Advertise, id=id)
#     if request.method == 'GET' and adver.user_id == request.user.id:
#         form = AdvertiseForm(instance=adver)
#         return render(request, 'direct/create_advertise.html', {'form': form, })
#     if request.method == 'POST':
#         form = AdvertiseForm(request.POST, request.FILES, instance=adver)
#         if form.is_valid():
#             form.save()
#             adver.allowed = False
#             adver.save()
#             messages.success(request, 'اگهی شما ایجاد شد ، پس از بررسی ادمین منتشر خواهد شد')
#         else:
#             messages.error(request, 'اطلاعات وارد شده صحیح نیست')
#         return redirect('direct:advertise')
#     else:
#         return redirect('topic:main')


def advertise(request):
    advs = Advertise.objects.all()
    for adv in advs:
        if adv.exp_date < datetime.now():
            adv.delete()
    advs = Advertise.objects.filter(allowed=True).order_by('-create')
    paginator = Paginator(advs, 2)
    page_num = request.GET.get('page')
    if advs.exists():
        advs = paginator.get_page(page_num)
    else:
        advs = None
    return render(request, 'direct/advertise.html', {'page_obj': advs, 'where': 'direct/advertise/', })


def contact_us(request):
    if request.method == 'GET':
        return render(request, 'direct/contact_us.html')
    if request.method == 'POST':
        sub = request.POST.get('subject')
        email = request.POST.get('email')
        contain = request.POST.get('contain')
        contain += '\n' + 'from : ' + email
        sus = EmailMessage(
            sub,
            contain,
            email,
            ('desprdo.kolbe@gmail.com',),
        )
        sus.send(fail_silently=False)
        messages.success(request, 'درخواست شما با موفقیت ارسال شد')
        return redirect('topic:main')

social/direct/templates/direct/advertise.html
{%extends 'topic/master.html'%}
{% block content %}
   <div> {% if user.action %}
        <p>تعداد اگهی های قابل ایجاد شما: {{ user.action }}</p>
        <a href="{% url 'direct:create_advertise'  %}">ایجاد اگهی</a>
        {% else %}
        <p>برای ایجاد اگهی باید اکشن کسب کرده باشید، برای کسب اکشن میتوانید با عنوان کردن مساله پر بازخورد و کسب بیشترین بازخورد در روز سه اکشن کسب کنید</p>
    {% endif %}
   </div>
{% for adv in page_obj %}
 <ul>
 <li>{{ adv.user.username }}</li>
 <li>{{ adv.subject }}</li>
 <li>{{ adv.text }}</li>
 {% if adv.image %}
 <li><img src="{{ adv.image.url}}" style="width: 100px " alt="عکس اگهی"></li>
 {% endif %}

 <li>{{ adv.create }}</li>
     {% if user.is_authenticated %}
     <li><a href="{% url 'direct:direct' user.id  adv.user.id %}">{{ adv.user}}دایرکت:</a></li>
         {% if adv.user_id == user.id %}
             <a href="{% url 'direct:modify_advertise' adv.id %}">ویرایش اگهی</a>
         {% endif %} 
         {% else %}
         <p><a href="{% url 'accounts:register' %}">لینک ثبت نام</a>برای ارتباط با کاربر لطفا ثبت نام کنید</p>
     {% endif %}

 </ul>
{% endfor %}
        {% include "topic/includes/paginate_page.html"%}

{% endblock %}

social/direct/templates/direct/contact_us.html
{%extends 'topic/master.html'%}
{% block content %}
<form method="POST">
  {% csrf_token %}
    <input type="text"   name="subject" placeholder="موضوع">
    <input type="email" {% if user.is_authenticated %} value={{ user.email }}{% endif %} required  oninvalid="alert('پر کردن فیلدهای مقابل اجباریست');" name="email" placeholder="ایمیل">
  <textarea   required oninvalid="alert('پر کردن فیلدهای مقابل اجباریست');"  name="contain" placeholder="توضیحات" cols="30" rows="10"></textarea>
  <button type="submit">ارسال ایمیل</button>
</form>
    <h3>شماره تماس </h3>
    <p>09910223229</p>
{% endblock %}

social/direct/templates/direct/create_advertise.html
{%extends 'topic/master.html'%}
{% block content %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
    {{ form.as_p }}
  <button type="submit">ایجاد اگهی </button>
</form>
{% endblock %}

social/direct/templates/direct/direct.html
{%extends 'topic/master.html'%}
{% block content %}
{% if not  roomate.block %}
<form action="{% url 'direct:block' roomate.id%}" method="POST">
    {% csrf_token%}
    <button type="submit"> بلاک کاربر</button>
</form>
 {% for direct in directs%}
    <ul>
      <li>{{direct.he_she}}</li>
      <li>{{direct.message}}</li>
  </ul>
 {% endfor %}
<form method="POST">
  {% csrf_token %}
    {{form.as_p}}
  <button type="submit">ارسال پاسخ </button>
</form>
{% else %}
<h1>اتاق گفتوگو توسط یکی از کاربران بلاک شده است </h1>
{% endif %}
{% endblock %}

social/direct/templates/direct/direct_list.html
{%extends 'topic/master.html'%}
{% block content %}
<ul>
    {% for person in persons %}
   <li><a href="{% url 'direct:direct' person.id user.id %}">{{person.username}}</a></li>
        {% if person in not_seens %}
           <span>پیام ناخوانده</span>
        {% endif %}
{% endfor%}
</ul>

{% endblock %}

social/direct/templates/direct/search.html
{%extends 'topic/master.html'%}
{% block content %}
<form method="POST">
    {% csrf_token %}

    <label> لیست افراد پیدا شده </label><br>
    <select class="form-control" name="search">
        <option value="">__انتخاب کنید __</option>
        {%for user in users%}
        <option value="{{user.id}}"> {{user.username}}</option>
        {% endfor %}
    </select><br>
    <button type="submit"> انتخاب شخص</button>
</form>
{% endblock %}