social/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [
                  path('login_costom/', views.login_costom, name='login_costom'),
                  path('logout_/', views.logout_, name='logout_'),
                  path('register/', views.register, name='register'),
                  path('profile/', views.profile, name='profile'),
                  path('rules/', views.Rules.as_view(), name='rules'),
                  path('ends/', views.Ends.as_view(), name='ends'),
                  path('password_check/', views.password_check, name='password_check'),
                  # path('phone_check/', views.phone_check, name='phone_check'),
                  path('forget_password/', views.ForgetPassword.as_view(), name='forget_password'),
                  path('password_reset_done/', views.ResetDone.as_view(), name='password_reset_done'),
                  path('confirm_password/<uidb64>/<token>/', views.ConfirmPassword.as_view(), name='confirm_password'),
                  path('confirm_done/', views.ConfirmDone.as_view(), name='confirm_done'),

              ]

social/direct/urls.py
from django.urls import path
from . import views

app_name = 'direct'
urlpatterns = [
    path('<int:idu>/<int:id_>/', views.direct, name='direct'),
    path('search/', views.search, name='search'),
    path('direct_list/', views.direct_list, name='direct_list'),
    path('new_notif/', views.new_notif, name='new_notif'),
    path('block/<int:id>/', views.block, name='block'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('advertise/', views.advertise, name='advertise'),
    path('create_advertise/', views.create_advertise, name='create_advertise'),
    # path('modify_advertise/<int:id>/', views.modify_advertise, name='modify_advertise'),
    path('alaki/',views.alaki,name='alaki'),
]

social/social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('topic/', include('topic.urls', namespace='topic')),
                  path('direct/', include('direct.urls', namespace='direct')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

social/topic/urls.py
from django.urls import path, re_path
from . import views

app_name = 'topic'
urlpatterns = [
    path('creat_topic/', views.creat_topic, name='creat_topic'),
    path('most_reacts/', views.MostReacts.as_view(), name='most_reacts'),
    re_path(r'public_topic/(?P<id>\d+)/(?P<slug_topic>[-\w]+)/$', views.public_topic, name='public_topic'),
    path('main/', views.main, name='main'),
    path('like/<int:id>/<str:like_>/<int:id_res>/', views.like, name='like'),
    path('like/<int:id>/<str:like_>/', views.like, name='like_topic'),
    # path('dislike/<int:id>/<str:like_>/<int:id_res>/', views.dislike, name='dislike'),
    path('user_topics/<int:id>/', views.user_topics, name='user_topics'),
    path('report/<int:id>/', views.report, name='report_top'),
    path('report/<int:id>/<int:id_res>/', views.report, name='report_rec'),

]

social/topic/models.py
from django.db import models
from accounts.models import *
from django_jalali.db import models as jmodels
from django.urls import reverse
from django.template.defaultfilters import slugify

from django.db.models.signals import post_save


class Series(models.Model):
    name = models.CharField(max_length=40)
    icon = models.CharField(max_length=40)

    def __str__(self):
        return str(self.name)


class FatherTopic(models.Model):
    report = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField()
    image = models.ImageField(upload_to='topic', blank=True, null=True)
    date = jmodels.jDateTimeField(auto_now_add=True)
    like = models.ManyToManyField(User, blank=True, related_name='like_users')
    dislike = models.ManyToManyField(User, blank=True, related_name='dislike_users')
    total_like = models.PositiveIntegerField(default=0)
    total_dislike = models.PositiveIntegerField(default=0)
    block = models.BooleanField(default=False)

    @property
    def total_like(self):
        return self.like.count()

    @property
    def total_dislike(self):
        return self.dislike.count()


class Response(FatherTopic):
    respon = models.ForeignKey('Topic', on_delete=models.CASCADE, blank=True, null=True, related_name='response')

    def __str__(self):
        return self.respon.title


# Create your models here.
class Topic(FatherTopic):
    series = models.ForeignKey(Series, on_delete=models.CASCADE)
    title = models.CharField(max_length=70)
    slug_topic = models.SlugField(allow_unicode=True, null=True, blank=True)
    total_responses = models.PositiveIntegerField(default=0)

    def get_absolute_url(self):
        return reverse('topic:public_topic', args=[self.id, self.slug_topic])

    def __str__(self):
        return str(self.title)


class SameTopics(models.Model):
    key = models.CharField(max_length=50)
    relateds = models.ManyToManyField(Topic, blank=True)


class View(models.Model):
    ip = models.CharField(max_length=30, blank=True, null=True)
    create = jmodels.jDateTimeField(auto_now_add=True, blank=True, null=True)


class MostReact(models.Model):
    day = jmodels.jDateField(auto_now_add=True)
    topic_title = models.CharField(max_length=70)
    topic_id = models.PositiveIntegerField()
    topic_total_responses = models.PositiveIntegerField(default=0)
    topic_slug = models.SlugField(allow_unicode=True, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.topic_slug:
            self.topic_slug = slugify(self.topic_title)
        return super().save(*args, **kwargs)


class Rewarded(models.Model):
    day = jmodels.jDateField()
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return str(self.day)

    # @property
    # def total_like(self):
    #     return self.like.count()
    #
    # total_like = models.PositiveIntegerField(default=0)
    # total_dislike = models.PositiveIntegerField(default=0)
    # @property
    # def total_dislike(self):
    #     sus = self.dislike.count()
    #     if sus >= 10:
    #         self.block = True
    #     return sus

social/topic/views.py
from datetime import timedelta

from django.contrib.auth.mixins import LoginRequiredMixin
from jdatetime import date
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from .form import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from accounts.models import *
from direct.models import *
from django.core.paginator import Paginator
from django.db.models import Max
from django.db.models import Q
from django.views import generic
from direct.views import new_notif

forbidens = {'امام', 'امام زمان', 'صلوات', 'کسکش', 'جنده', 'جنده', 'بیناموس', 'بی ناموس',
             'کیر', 'بیشرف', 'پدر سگ', 'جاکش', 'حرومزاده', 'بیشعور', 'بی شعور', 'انتر'
    , 'پفیوز', 'کثافت', 'ریدم دهن', }


# Create your views here.
@login_required(login_url='accounts:login_costom')
def creat_topic(request):
    if request.method == 'GET':
        form = CreatForm()
        names = Series.objects.values('name', 'icon', )
        return render(request, 'topic/creat_topic.html', {'form': form, 'names': names, })
    if request.method == 'POST':
        form = CreatForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            slug = slugify(data['title'])
            top = Topic(series=data['series'], title=data['title'], description=data['description']
                        , image=data['image'], user_id=request.user.id, slug_topic=slug)
            for item in forbidens:
                if item in top.title or item in top.description:
                    messages.warning(request,
                                     'از بکار بردن کلمات ممنوعه بپرهیزید, تاپیک شما توسط ادمین بررسی و در صورت مورد دار نبودن منتشر خواهد شد!')
                    top.block = True
            top.save()
            if not top.block:
                topel = get_object_or_404(Topic, id=top.id, series=data['series'], title=data['title'])
                id = str(topel.id)
                return redirect('topic:public_topic', id, slug)
        messages.warning(request, 'الاعات وارد شده صحیح نیست')
        return redirect('topic:creat_topic')


@login_required(login_url='accounts:login_costom')
def like_dislike_of_user(request, objs):
    context_liked = []
    context_disliked = []
    for status in objs:
        if status.like.filter(id=request.user.id).exists():
            context_liked.append(status.id)
        if status.dislike.filter(id=request.user.id).exists():
            context_disliked.append(status.id)
    return {'context_liked': context_liked, 'context_disliked': context_disliked, }


def public_topic(request, id, slug_topic):
    if request.method == 'GET':
        form = ResponseToTopicForm()
        topic = get_object_or_404(Topic, id=id, slug_topic=slug_topic, block=False)
        sames = SameTopics.objects.values_list('key', 'relateds')

        for item in sames:
            # return HttpResponse(topic.title)
            if item[0] in topic.title or item[0] in topic.description:
                item[1].add(topic)
        topic.total_responses = topic.response.count()
        topic.save()
        mosted = MostReact.objects.filter(day=date.today()).exists()
        # return  HttpResponse()
        if not mosted:
            MostReact(day=date.today(), topic_title=topic.title, topic_id=topic.id,
                      topic_total_responses=topic.total_responses).save()
        if mosted and topic.date.date() == date.today():
            most = get_object_or_404(MostReact, day=date.today())
            if most.topic_total_responses < topic.total_responses:
                most.topic_total_responses = topic.total_responses
                most.topic_id = topic.id
                most.topic_title = topic.title
                most.topic_slug = slugify(most.topic_title)
                most.save()

        serie = get_object_or_404(Series, id=topic.series.id)
        responses = topic.response.filter(block=False)
        paginator = Paginator(responses, 3)
        page_num = request.GET.get('page')
        if responses.exists():
            responses = paginator.get_page(page_num)
        else:
            responses = None
        context = {'form': form, 'topic': topic, 'page_obj': responses, 'series': serie,
                   'like': 'like', 'dislike': 'dislike', 'where': topic.get_absolute_url(), }
        if request.user.is_authenticated and responses:
            context_response = like_dislike_of_user(request, responses)
            chop = (topic,)
            context_topic = like_dislike_of_user(request, chop)
            context_topic['topic_like'] = context_topic.pop('context_liked')
            context_topic['topic_dislike'] = context_topic.pop('context_disliked')
            context.update(context_response)
            context.update(context_topic)

        return render(request, 'topic/public_topic.html', context)
    if request.method == 'POST':
        res = request.POST.get('res')
        form = ResponseToTopicForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            receive = Response(respon_id=res, user_id=request.user.id, description=data['description'],
                               image=data['image'], )
            for item in forbidens:
                if item in receive.description:
                    messages.warning(request,
                                     'از بکار بردن کلمات ممنوعه بپرهیزید, پاسخ شما توسط ادمین بررسی و در صورت مورد دار نبودن منتشر خواهد شد!')
                    receive.block = True
            receive.save()
            return redirect('topic:public_topic', id, slug_topic)
        messages.warning(request, 'اطلاعات وارد شده صحیح نیست')
        return redirect('topic:public_topic', id, slug_topic)


def main_log_parameters(request, value, sere):
    ip = request.META.get('REMOTE_ADDR')
    if not View.objects.filter(ip__exact=ip).exists():
        sus = View.objects.create(ip=ip)
        sus.save()
    views = View.objects.values_list().count()
    series = Series.objects.all()
    result = Topic.objects
    if value:
        if sere:
            sere = get_object_or_404(Series, name__exact=sere)
            tops = result.filter(title__icontains=value, series__exact=sere.id, block=False).order_by('-date')
        else:
            tops = result.filter(title__icontains=value, block=False).order_by('-date')
    else:
        if sere:
            sere = get_object_or_404(Series, name__exact=sere)
            tops = result.filter(block=False, series__exact=sere.id).order_by('-date')
        else:
            tops = result.filter(block=False, ).order_by('-date')
    paginator = Paginator(tops, 3)
    page_num = request.GET.get('page')
    if tops.exists():
        topics = paginator.get_page(page_num)
    else:
        topics = None
    return {'topics': topics, 'search': value, 'sere': sere, 'views': views, 'series': series, 'where': 'topic/main/', }


# def start_day(request):
#     most = MostReact.objects.filter(day=date.today() - timedelta(days=1))
#     rewarded = Rewarded.objects.filter(day=date.today() - timedelta(days=1))
#     if not rewarded.exists() and most.exists():
#         most_react_of_yesterday = MostReact.objects.get(day=date.today() - timedelta(days=1))
#         topic = get_object_or_404(Topic, id=most_react_of_yesterday.topic_id)
#         user = User.objects.get(id=topic.user.id)
#         user.action += 3
#         user.save()
#         Rewarded(day=date.today() - timedelta(days=1), user_id=topic.user.id).save()


def main(request):
    mosts = MostReact.objects.order_by('-day')[0:5]
    value = request.GET.get('search')
    sere = request.GET.get('sere')
    new = new_notif(request)
    custom = main_log_parameters(request, value, sere)
    custom.update({'mosts': mosts})
    if new:
        custom.update({'new': new})
    return render(request, 'topic/main.html', custom)


@login_required(login_url='accounts:login_costom')
def like(request, id, like_, id_res=None):
    message = ''
    topic = get_object_or_404(Topic, id=id, block=False)
    if id_res:
        topic = get_object_or_404(Response, id=id_res, block=False)
    if like_ == 'like':
        if topic.like.filter(id=request.user.id).exists():
            topic.like.remove(request.user)
            message = 'remove like'
        elif topic.dislike.filter(id=request.user.id).exists():
            message = 'do noting'
        else:
            topic.like.add(request.user)
            message = 'like'
    elif like_ == 'dislike':
        if topic.dislike.filter(id=request.user.id).exists():
            topic.dislike.remove(request.user)
            message = 'remove dislike'
        elif topic.like.filter(id=request.user.id).exists():
            message = 'do noting'
        else:
            topic.dislike.add(request.user)
            message = 'dislike'
        topic.save()
        if topic.total_dislike >= 10:
            topic.delete()
            if not Topic.objects.filter(id=id, block=False).exists():
                messages.warning(request, 'تاپیک حذف شد')
                return redirect('topic:main')
    return HttpResponse(message)


# class UserTopics(LoginRequiredMixin,generic.DetailView):
#     template_name = 'topic/user_topics.html'
#     # pk_url_kwarg = 'pk'
#     model = User
#
#
#     def get_context_data(self, **kwargs):
#         pk = self.kwargs.get('pk')
#         context = super().get_context_data(**kwargs)
#         topics = Topic.objects.filter(user_id=pk, block=False)
#         con = {'topics': topics, 'pk': pk, }
#         context.update(con)
#         return context


def user_topics(request, id):
    if request.method == 'GET':
        tops = Topic.objects.filter(user_id=id, block=False).order_by('-date')
        paginator = Paginator(tops, 3)
        page_num = request.GET.get('page')
        if tops.exists():
            # return HttpResponse(page_num)

social/topic/templates/topic/creat_topic.html
{%extends 'topic/master.html'%}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <ul style="margin : 100px ; padding: 10px">
        {{ form.as_p }}
        <li style="margin-top: 15px"><button type="submit">ایجاد تاپیک</button> </li>
    </ul>
</form>

{% endblock %}

social/topic/templates/topic/main.html
{% extends "topic/master.html"%}
{% block content %}
<h1>تعداد بازدید : {{ views }}</h1>
{% if user.is_authenticated %}
<h1>تعداد اکشن:{{ user.action }}</h1>
{% if user.action  %}
    <a href="{% url 'direct:create_advertise' %}"><h1>اکشن دارد</h1></a>
{% endif %}
{% endif %}

<table>
    <thead>
 <th>نام کاربری</th>
 <th>تاپیک</th>
</thead>
    <tbody>
     {%for topic in topics%}
    <tr>
        <td><a href="{% url 'topic:user_topics' topic.user.id %}">{{topic.user.username}}</a></td>
        <td><a href="{{ topic.get_absolute_url }}">{{topic.title}} </a> </td>
    </tr>
     {% endfor %}
    </tbody>
</table>
    {% include "topic/includes/paginator.html"%}
{% endblock%}
{% block alarms %}
     {% if user.is_authenticated %}
               {% if new %}
                <div class="more_button" >پیام جدید<i >     {{ new }}</i></div>
               {% endif %}
            <div class="more_button" ><a href="{% url 'direct:direct_list'%}">بخش دایرکت</a></div>
           {% endif%}
{% endblock %}
{% block log %}
    {% if where %}
               <h2> تاپیک های پربازدید</h2>
            <div class="left_col_box">
                {% for most in mosts %}
                  <h3>{{ most.day }}</h3>
                    <a href="{% url 'topic:public_topic' most.topic_id most.topic_slug %}"><span>{{ most.topic_title }}</span></a>
                {% endfor %}
                <p><a href="{% url 'topic:most_reacts' %}"> صغحه تاپیکهای پربازدید </a></p>

                <div class="blog_box">

                    Suspendisse vitae neque eget ante tristique vestibulum. Pellentesque vitae magna.<br/>
                    Posted by in <a href="#"><span>Videos</span></a><br/>
                    14 December 2020
                </div>

            </div>

            {% endif %}
{% endblock %}
{% block footer %}
            {% load main_filter %}
            {% for foo in series %}
                 <a href="{{ where }}{% get_filters topics.number  'page' request.GET.urlencode %}&sere={{ foo }}">{{ foo.name }}</a> |
            {% endfor %}
            <br/>
             <a href="{{ where }}"><strong>حذف فیلترها</strong></a>
{% endblock %}

social/topic/templates/topic/master.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title> سایت </title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <base href="/">

</head>
<body>
<!--
This is a free CSS template provided by templatemo.com

-->

<div id="templatemo_container">

    <div id="templatemo_header">
        <div id="templatemo_title">
            <div id="templatemo_sitetitle">corsi <span>site</span></div>
        </div>


            <div id="templatemo_login">
                {% if user.is_authenticated %}
            <form method="get" action="{% url 'direct:search' %}">
                <input class="inputfield" placeholder="جستوجو افراد" name="search" type="text"/>
                <input class="button" type="submit"/>
            </form>
                {% endif %}
             <form method="get"  >
                <input class="inputfield" placeholder="جستوجو تاپیک" name="search" type="text"/>
                <input class="button" type="submit"/>
            </form>
        </div>


    </div>

    <div id="templatemo_banner">
        <div id="templatemo_banner_text">
            <div id="banner_title">Welcome To Music Store</div>
            <p>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc quis sem nec tellus blandit tincidunt.
                Duis vitae velit sed dui malesuada dignissim. Donec mollis aliquet ligula. Lorem ipsum dolor sit amet,
                consectetuer adipiscing elit. Nunc quis sem nec tellus blandit tincidunt.
            </p>
          {% block alarms %}
            {% endblock %}
        </div>
    </div>

    <div id="templatemo_menu">
        <ul>
            <li> {%if request.user.is_authenticated %}<a href="{% url 'accounts:logout_'%}">خروج</a>
                {%else%}
                <a href="{% url 'accounts:login_costom'%}"{% if request.resolver_match.url_name == 'login_costom'%}class="current"{% endif %}>ورود</a>{% endif %}
{#                <a href=" href=""#}
{#                </a>{% if request.resolver_match.url_name == 'register' %}<a href="{% url 'accounts:register'%}" >ثبت نام</a>{% endif%}#}
{#                 #}
            </li>

        {% if not user.is_authenticated %}
            <li>
                <a href="{% url 'accounts:register'%}"{% if request.resolver_match.url_name == 'register'%}class="current"{% endif %}>ثبت نام</a>
            </li>
         {% endif %}
            <li><a href="{% url 'topic:main'%}"
                   class="{% if request.resolver_match.url_name == 'main'%}current{% endif%}">
                منو اصلی</a></li>
            {% if user.is_authenticated %}
            <li><a href="{{ user.get_absolute_url }}"
                   class="{% if request.resolver_match.url_name == 'profile'%}current{% endif%}">پروفایل</a></li>
            {% endif %}

            {%if request.user.is_authenticated %}
            <li><a href="{% url 'topic:creat_topic'%}"
                   class="{% if request.resolver_match.url_name == 'creat_topic'%}current{% endif%}">افزودن تاپیک</a>
            </li>
            {% endif %}
            <li><a href="{% url 'accounts:ends'%}"
                   class="{% if request.resolver_match.url_name == 'ends'%}current{% endif%}">اهداف سایت</a>
            </li>
            <li><a href="{% url 'accounts:rules'%}"
                   class="{% if request.resolver_match.url_name == 'rules'%}current{% endif%}"> قوانین سایت</a>
            </li>

            <li><a href="{% url 'direct:advertise' %}"
            class="{% if request.resolver_match.url_name == 'advertise'%}current{% endif%}">فروشگاه کاربران</a></li>
            <li><a href="{% url 'direct:contact_us' %}" class="lastmenu {% if request.resolver_match.url_name == 'contact_us'%}current{% endif%}">تماس با ما</a></li>

        </ul>
    </div>


    <div id="templatemo_content">

        <div id="templatemo_left_column">
            {% block log%}
            {% endblock%}


        </div>
        <!--            start of list-->
        {%if messages %}
        {%for message in messages%}
        {% if message.tags %}<h4 class="alert alert-{{message.tags}}" style="padding: 10px ;color: red ">{{message}}</h4>{% endif%}
        {% endfor%}
        {% endif%}


        {% block content%}
        {% endblock %}
    </div>

    <div id="templatemo_footer">
    {% block footer%}
        {% endblock %}

        <!-- Credit: www.templatemo.com -->
    </div>
</div>
<!--  Designed by w w w . t e m p l a t e m o . c o m  -->
<!-- templatemo 047 music -->
<!--
Music Template
http://www.templatemo.com/preview/templatemo_047_music
-->
<link href="../../static/templatemo_style.css" rel="stylesheet" type="text/css"/>
<script src="{% static 'js/accounts.js'%}"></script>
</body>
</html>

social/topic/templates/topic/public_topic.html
{% extends 'topic/master.html' %}
{% block content %}
    {% load thumbnail %}
    <div style="background-color: #400a0a">
        {% thumbnail topic.user.image "75x75" as img %}
            <p>self emage: <img src="{{ img.url }}" alt="عکس پروفایل"></p>
        {% endthumbnail %}
        <p>title:{{ topic.title }}</p>
        <p>series:{{ topic.series }}</p>
        <p>user:{{ topic.user }}</p>
        <p>description:{{ topic.description }}</p>
        {% if topic.image %}
            <p>image: <img src="{{ topic.image.url }}" alt="عکس تاپیک"></p>
        {% endif %}

        <p>date:{{ topic.date }}</p>
        <p>block:{{ topic.block }}</p>
        <p>like:<span id="like_num">{{ topic.total_like }}</span></p>
        <p>dislike:<span id="dislike_num">{{ topic.total_dislike }}</span></p>
         <p>total_response: {{ topic.total_responses }}</p>
        <form action="{% url 'topic:report_top' topic.id %}" method="POST">
            {% csrf_token %}
            <button type="submit">گزارش تاپیک</button>
        </form>
    {% if user.is_authenticated %}
                <div>
                    {% if topic.id in topic_like %}
                        <button type="button" style="background-color:#ff01bd"><a href="{% url 'topic:like_topic' topic.id like  %}">like</a></button>
                    {% else %}
                        <button type="button"><a href="{% url 'topic:like_topic' topic.id like  %}">like</a></button>
                    {% endif %}
                    {% if topic.id in topic_dislike %}
                        <button type="button" style="background-color:#FF01BD"><a href="{% url 'topic:like_topic' topic.id dislike  %}">dislike</a>
                        </button>
                    {% else %}
                        <button type="button"><a href="{% url 'topic:like_topic' topic.id dislike  %}">dislike</a></button>
                    {% endif %}
                    <button type="button" id="replay">replay</button>
                </div>
            {% endif %}

    </div>
    <div>
    </div>
    <div>
        {% for top in page_obj %}
            <p>user: {{ top.user.username }}</p>
            <p>description: {{ top.description }}</p>
            <p>image: {{ top.image }}</p>
            <p>date: {{ top.date }}</p>
            <p>total_like: {{ top.total_like }}</p>
            <p>total_dislike: {{ top.total_dislike }}</p>
            <p>
            <form action="{% url 'topic:report_rec' topic.id top.id %}" method="POST">
                {% csrf_token %}
                <button type="submit">گزارش تاپیک</button>
            </form></p>
            {% if user.is_authenticated %}
                <div>
                    {% if top.id in context_liked %}
                        <button type="button" style="background-color:#FF01BD"><a href="{% url 'topic:like' topic.id like top.id %}">like</a></button>
                    {% else %}
                        <button type="button"><a href="{% url 'topic:like' topic.id like top.id %}">like</a></button>
                    {% endif %}
                    {% if top.id in context_disliked %}
                        <button type="button" style="background-color:#FF01BD"><a href="{% url 'topic:like' topic.id dislike top.id %}">dislike</a>
                        </button>
                    {% else %}
                        <button type="button"><a href="{% url 'topic:like' topic.id dislike top.id %}">dislike</a></button>
                    {% endif %}
                    <button type="button" id="replay">replay</button>
                </div>
            {% endif %}
        {% endfor %}
    </div>


    {% if user.is_authenticated %}
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" name="res" value="{{ topic.id }}">
            <button type="submit">ارسال نظر</button>
        </form>
    {% endif %}
        {% include "topic/includes/paginate_page.html"%}

{#    <div>#}
{#     <ul class="pagination">#}
{#        {% if responses.has_previous %}#}
{#        <li class="page-item "><a class="page-link" href="{{ topic.get_absolute_url }}?page={{ responses.previous_page_number }}"#}
{#                                  aria-label="Previous">قبلی</a></li>#}
{#        <li class="page-item "><a class="page-link" href="{{ topic.get_absolute_url }}?page={{ responses.previous_page_number }}"#}
{#                                  aria-label="Previous">{{ responses.previous_page_number }}</a></li>#}
{#        {% endif %}#}
{##}
{#         <li class="page-item active"><a class="page-link" href="{{ topic.get_absolute_url }}?page={{ responses.number }}" aria-label="next">{{ responses.number }}</a></li>#}
{##}
{#        {% if responses.has_next %}#}
{#        <li class="page-item "><a class="page-link" href="{{ topic.get_absolute_url }}?page={{ responses.next_page_number }}"#}
{#                                  aria-label="next">{{ responses.next_page_number }}</a></li>#}
{#        <li class="page-item "><a class="page-link" href="{{ topic.get_absolute_url }}?page={{ responses.next_page_number }}"#}
{#                                  aria-label="next">بعدی</a></li>#}
{#        {% endif %}#}
{#    </ul>#}
{#    </div>#}
{% endblock %}