social/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [
                  path('login_costom/', views.login_costom, name='login_costom'),
                  path('logout_/', views.logout_, name='logout_'),
                  path('register/', views.register, name='register'),
                  path('profile/', views.profile, name='profile'),
                  path('rules/', views.Rules.as_view(), name='rules'),
                  path('ends/', views.Ends.as_view(), name='ends'),
                  path('password_check/', views.password_check, name='password_check'),
                  # path('phone_check/', views.phone_check, name='phone_check'),
                  path('forget_password/', views.ForgetPassword.as_view(), name='forget_password'),
                  path('password_reset_done/', views.ResetDone.as_view(), name='password_reset_done'),
                  path('confirm_password/<uidb64>/<token>/', views.ConfirmPassword.as_view(), name='confirm_password'),
                  path('confirm_done/', views.ConfirmDone.as_view(), name='confirm_done'),

              ]

social/social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('topic/', include('topic.urls', namespace='topic')),
                  path('direct/', include('direct.urls', namespace='direct')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

social/topic/urls.py
from django.urls import path, re_path
from . import views

app_name = 'topic'
urlpatterns = [
    path('creat_topic/', views.creat_topic, name='creat_topic'),
    path('most_reacts/', views.MostReacts.as_view(), name='most_reacts'),
    re_path(r'public_topic/(?P<id>\d+)/(?P<slug_topic>[-\w]+)/$', views.public_topic, name='public_topic'),
    path('main/', views.main, name='main'),
    path('like/<int:id>/<str:like_>/<int:id_res>/', views.like, name='like'),
    path('like/<int:id>/<str:like_>/', views.like, name='like_topic'),
    # path('dislike/<int:id>/<str:like_>/<int:id_res>/', views.dislike, name='dislike'),
    path('user_topics/<int:id>/', views.user_topics, name='user_topics'),
    path('report/<int:id>/', views.report, name='report_top'),
    path('report/<int:id>/<int:id_res>/', views.report, name='report_rec'),

]

social/accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse
from sorl.thumbnail import ImageField as ThumbImage
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django_jalali.db import models as jmodels


# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, phone, username, password, email):
        if not phone:
            raise ValueError('شماره همراه خود را وارد کنید')
        if not email:
            raise ValueError('ایمیل خود را وارد کنید')
        if not username:
            raise ValueError('نام کاربری خود را وارد کنید')
        user = self.model(username=username, phone=phone, email=email)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone, username, password, email):
        user = self.create_user(phone, username, password, email)
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    username = models.CharField(max_length=25, unique=True)
    phone = models.PositiveIntegerField(unique=True)
    email = models.EmailField(blank=True, null=True, unique=True)  # REMOVE BLANK AND NULL FOR LATER
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False, null=True)
    is_block = models.BooleanField(default=False)
    action = models.PositiveIntegerField(default=0)
    GENDER = [('M', 'مرد'), ('F', 'زن')]
    sex = models.CharField(choices=GENDER, max_length=1, blank=True, null=True)
    image = ThumbImage(upload_to='user', default='1.jpg', blank=True, null=True)
    bio = models.TextField(max_length=500, blank=True, null=True)
    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = ('username', 'email',)
    objects = UserManager()
    is_superuser = models.BooleanField(default=False)

    def __str__(self):
        return self.username

    def __unicode__(self):
        return self.image.path

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    def get_absolute_url(self):
        return reverse('accounts:profile')

social/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .form import *
from accounts.models import User
from topic.models import Topic
from topic.views import main_log_parameters
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from random import randint
from kavenegar import *
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views import generic, View
from django.contrib.auth.forms import UserCreationForm
from sorl.thumbnail import get_thumbnail


# Create your views here.
class Rules(generic.TemplateView):
    template_name = 'accounts/rules.html'


class Ends(generic.TemplateView):
    template_name = 'accounts/ends.html'


def send_sms(request, number, template, message):
    try:
        api = KavenegarAPI(
            '66794E75437974365963452B2F367331586E656E6A37722F4F6F5550584E534F4A48556E6B4D725238334D3D')
        params = {
            'receptor': number,
            'template': template,
            'token': message,
            'type': 'sms',  # sms vs call
        }
        response = api.verify_lookup(params)
        print(response)
    except APIException as e:
        print(e)
    except HTTPException as e:
        print(e)


def login_costom(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'accounts/login_costom.html', {'form': form, })
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            try:
                user = authenticate(request, phone=User.objects.get(username=data['phone']).phone,
                                    password=data['password'])
            except:
                user = authenticate(request, phone=data['phone'], password=data['password'])
            if user:
                if not user.is_block:
                    login(request, user)
                    return redirect('topic:main')
                else:
                    messages.warning(request, 'کاربری شما تعلیق شده است')
                    return redirect('accounts:register')
            else:
                messages.warning(request, 'اطلاعات وارد شده صحیح نیست')
                return redirect('accounts:login_costom')
        else:
            messages.warning(request, 'اطلاعات وارد شده صحیح نیست')
            return redirect('accounts:login_costom')


def register(request):
    global random_code, number, reguser
    random_code = randint(1000, 9999)
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'accounts/register.html', {'form': form, })
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            number = data['phone']
            if User.objects.filter(phone=number).exists():
                moser = User.objects.get(phone=number)
                if not moser.is_active:
                    reguser = moser
                else:
                    messages.success(request, 'کاربری شما فعال است!')
                    return redirect('accounts:login_costom')
            else:
                reguser = User.objects.create_user(username=data['username'], phone=number,
                                                   password=data['password_2'], email=data['email'])

            messages.success(request, ' برای فعلسازی کاربری لطفا پیامک ارسال شده را برای ما ارسال کنید!')
            send_sms(request, (number,), 'verify', random_code)
            return redirect('accounts:phone_check')
        else:
            messages.warning(request, 'اطلاعات وارد شده صحیح نمیباشند')
            return redirect('accounts:register')


def logout_(request):
    logout(request)
    return redirect('accounts:login_costom')


@login_required(login_url='accounts:login_costom')
def profile(request):
    if request.method == 'GET':
        user_form = UserForm(instance=request.user)
        return render(request, 'accounts/profile.html',
                      {'user_form': user_form, })
    if request.method == 'POST':
        user_form = UserForm(request.POST, request.FILES, instance=request.user, )
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'پروفایل با موفقیت ویرایش شد', 'success')
            return redirect('topic:main')
        else:
            messages.warning(request, 'اطلاعات وارد شده صحیح نیست!', 'warning')
            return redirect('accounts:profile')


@login_required(login_url='accounts:login_costom')
def password_check(request):
    if request.method == 'GET':
        form = PasswordChangeForm(request.user)
        return render(request, 'accounts/password_check.html', {'form': form})
    if request.method == 'POST':
        pass_form = PasswordChangeForm(request.user, request.POST)
        if pass_form.is_valid():
            pass_form.save()
            update_session_auth_hash(request, pass_form.user)
            messages.success(request, 'پسورد با موفقیت نغییر کرد ')
            return redirect('topic:main')
        else:
            messages.warning(request, 'تغیرات پسورد ناموفق ')
            return redirect('accounts:profile')


class ForgetPassword(auth_views.PasswordResetView):
    template_name = 'accounts/reset_password.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/link.html'


class ResetDone(auth_views.PasswordResetDoneView):
    template_name = 'accounts/reset_password_done.html'


class ConfirmPassword(auth_views.PasswordResetConfirmView):
    template_name = 'accounts/confirm_password.html'
    success_url = reverse_lazy('accounts:confirm_done')


class ConfirmDone(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/confirm_done.html'


# def phone_check(request):
#     if request.method == 'GET':
#         form = CodeForm()
#         return render(request, 'accounts/phone_check.html', {'form': form})
#     if request.method == 'POST':
#         form = CodeForm(request.POST)
#         if form.is_valid():
#             data = form.cleaned_data
#             if data['code'] == random_code:
#                 reguser.is_active = True
#                 reguser.save()
#                 messages.success(request, 'حساب کاربری برای شما فعال شد')
#                 return redirect('accounts:login_costom')
#             else:
#                 messages.warning(request, 'اطلاعات وارد شده صحیح نیست')
#                 return redirect('accounts:phone_check')

social/accounts/templates/accounts/confirm_done.html
{%extends 'topic/master.html'%}
{% block content %}
    <p>پسورد شما با موفقیت تغییر یافت</p>
{% endblock %}

social/accounts/templates/accounts/confirm_password.html
{% extends 'topic/master.html' %}
{% block content %}
    {% if validlink %}
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">تغییر پسورد</button>
        </form>
    {% endif %}
{% endblock %}

social/accounts/templates/accounts/ends.html
{%extends 'topic/master.html'%}
{% block content %}
<h1>اهداف سایت</h1>
    <p>  ضمن همه گیری شبکه های اجتماعی ، سایت /// قصد دارد تا محیطی راحت و جذابی را برای شما عزیزان بوجود بیاورد که باتبادل نظرات و تجربیات  از سوی شما کاربران دیگر باعث افزایش سطح اگاهی و دانش کاربران شود</p>
   <p>ضمن اینکه ممکن است سوالات مطرح شده از سوی شما ، سوالات کاربران خارج از سایت نیز باشند و یا سوالات کاربران دیگر سوالات شما باشند.پس از اینرو موتورهای جستو جو از طریق سایت من قادر به راهنمایی شما و دیگر کاربران خواهند بود </p>
{% endblock %}

social/accounts/templates/accounts/link.html
ایمیل خود را تایید کنید
{{ protocol }}://{{ domain }}{% url 'accounts:confirm_password' uidb64=uid token=token %}

social/accounts/templates/accounts/login_costom.html
{% extends "topic/master.html"%}


{% block content %}
    <h2> فرم ورود </h2>
  <form method="POST" >
    {% csrf_token %}
    {{form.as_p}}
     <button type="submit">ورود</button>
</form>
<p> حساب کاربری ندارید؟ <a href="{% url 'accounts:register'%}">کلیک کنید</a>
</p><p><a href="{% url 'accounts:forget_password' %}">رمز عبور خود را فراموش کرده اید؟</a></p>

{#{% if where == 'accounts/register/'%} <p>مشخصات خود را بدقت وارد کنید، نام کاربری و شماره همراه شما منحصر به فرد هستن، بازیابی رمز عبور هم تنها از طریق ایمیل انجام میشود</p>#}
{#    <p>حساب کاربری دارید؟ <a href="{% url 'accounts:login_costom'%}">کلیک کنید</a>#}
{#</p><p>شما با ثبت نام در سایت موافقت خود را با <a href="{% url 'accounts:rules' %}">قوانین و مقررات سایت</a> اعلام میکنید</p> {% endif %}#}
{% endblock%}

social/accounts/templates/accounts/password_check.html
{% extends 'topic/master.html'%}
{% block content%}
<form method="POST">
    {% csrf_token %}
    <input type="password" placeholder="پسورد قبلی" name="old_password">
    <input type="password" placeholder="پسورد جدید" name="new_password1">
    <input type="password" placeholder="تکرار پسورد جدید" name="new_password2">
    <button type="submit"> تکمیل شد </button>
</form>
{% endblock%}

social/accounts/templates/accounts/phone_check.html
{% extends 'topic/master.html'%}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <input type="number" required name="code">
    <button type="submit">تایید کد</button>
</form>
{% endblock%}

social/accounts/templates/accounts/profile.html
{% extends 'topic/master.html' %}
{% block content %}
    {% load thumbnail %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div style="background-color : aqua;height: 40px;font-size: 30px;margin-top: 25px;width: 400px; margin-left: 550px">
            نمایش پروفایل
        </div>
        <ul id="profile">
            <li style="padding:10px">{% thumbnail user.image '75x75' crop="center" as img %}
                <img src="{{ img.url }}" alt="عکس پروفایل">
            {% endthumbnail %}</li>
            <li style="padding:10px"><input type="text" style="padding: 5px" name="email"
                                            value="{% if user.email %}{{ user.email }}{% endif %}" placeholder="ایمیل">
            </li>
            <li style="padding:10px ; "><input type="text" style="padding: 5px" name="username"
                                               value="{{ user.username }}" placeholder="نام کاربری"></li>
            <li style="padding:10px"><input type="text" style="padding: 5px" name="bio" placeholder="بیو"
                                            value="{% if user.bio %}{{ user.bio }}{% endif %}"></li>
            <li style="padding:10px"><input type="file" style="padding: 5px" name="image" placeholder="عکس">
                {{ user.image }}</li>
            <li>
                <label> جنسیت </label>
                <select class="form-control" name="sex">
                    <option value="">__انتخاب کنید __</option>
                    <option value="M" {% if user.sex == 'M' %} selected {% endif %}> مرد</option>
                    <option value="F" {% if user.sex == 'F' %} selected {% endif %}> زن</option>
                </select>
            </li>

            <li><a href="{% url 'accounts:password_check' %}"> تغییر پسورد </a></li>
            <li style="padding:10px ; " hidden id="password_check"><input type="text" style="padding: 5px"></li>
            <li>
                <button id='sub' type="submit"> اعمال تغیرات</button>
            </li>

        </ul>


    </form>
{% endblock %}

social/accounts/templates/accounts/register.html
{% extends "topic/master.html"%}
{% block content %}
    <h2> فرم ثبت نام </h2>
  <form method="POST" >
    {% csrf_token %}
    {{form.as_p}}
     <button type="submit">ثبت نام</button>
</form>


 <p>مشخصات خود را بدقت وارد کنید، نام کاربری و شماره همراه شما منحصر به فرد هستن، بازیابی رمز عبور هم تنها از طریق ایمیل انجام میشود</p>
    <p>حساب کاربری دارید؟ <a href="{% url 'accounts:login_costom'%}">کلیک کنید</a>
</p><p>شما با ثبت نام در سایت موافقت خود را با <a href="{% url 'accounts:rules' %}">قوانین و مقررات سایت</a> اعلام میکنید</p>
{% endblock%}

social/accounts/templates/accounts/reset_password.html
{%extends 'topic/master.html'%}
{% block content %}
<form method="POST">
  {% csrf_token %}
    {{ form }}
  <button type="submit">ارسال ایمیل</button>
</form>
{% endblock %}

social/accounts/templates/accounts/reset_password_done.html
{%extends 'topic/master.html'%}
{% block content %}
    <p>   لینک مربوط به تغیر پسورد برای شما ارسال شد ,در صورت عدم دریافت ایمیل لیست سپم خود را چک کنید و برای دریافت مجدد ایمیل ، ادرس ایمیل سایت را از حالت  اسپم خارج کنید</p>
{% endblock %}

social/accounts/templates/accounts/rules.html
{%extends 'topic/master.html'%}
{% block content %}
<h1>شرایط و قوانین سایت</h1>
    <p>با سلام وعرض ادب و احترام خدمت شما عزیزان</p>
    <p>سایت //////// شامل قوانین و مقرراتی است که جهت رضامندی و ارامش شما فراهم شده است و شامل قوانین زیر است </p>
    <ul>
    <li>خواهشمندیم از هر گونه توهین و بی احترامی به دیگران بپرهیزید. در صورت مشاهده به شما اخطار و در صورت عدم رعایت حرمت و احترام اشخاص ، سایت من مجبور ب تعلیق حساب کاربری شما خواهد شده که در این صورت دیگر قادر به ورود به سایت با حساب کاربری خود نخواهید بود </li>
    <li>از انجام هر گونه جر وبحث بیمورد خودداری کنید</li>
    <li>خدمات سایت برای شما کاملا رایگان است. لذا هرگونه در خواست وجه از سمت سایت ///// نیست و سایت ///هیچ گونه مسولیتی در این قبال ندارد</li>
    <li>هر حساب کاربری شامل نام کاربری، ایمیل، تلفن همراه منحصر به فرد است. لطفا هنگام ثبت نام، نام کاربری، و ایمیل وتلفن همراه خود را در جایی یادداشت کنید. زیرا در صورت فراموشی رمز عبور تنها ورود شما از طریق ایمیل امکانپذیر خواهد بود</li>
    <li>از انجام هر گونه فحاشی و بی احترامی به اشخاص سیاسی و مذهبی خودداری کنید. سایت //// هیچ گونه مسولیتی در این مورد ندارد و مسولیت کلیه اضهارات کاربر به عهده خود کاربر میباشد.در صورت مشاهده اخطار وحذف تاپیک و در صورت لزوم سایت /////////// مجبور به تعلیق حساب کاربری شما خواهد شد </li>
    <li>انجام تبلیغات در پستها خلاف قوانین سایت است، در صورت مشاهده کاربری شما تعلیق خواهد شد.انجام تبلیغات فقط در صفحه فروشگاه کاربران و تنها برای کاربرانی امکانپذیر است که بیشترین بازخورد را در روز کسب کرده باشند. با کسب بیشترین بازخورد در روز سایت ///// ،به کاربر 3 اکشن تعلق میگیرد ، وبه ازای هر اکشن کاربر قادر به درج یک اگهی در فروشگاه کاربران خواهد بود </li>
    </ul>
{% endblock %}